---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-data
  namespace: wsp-sentry
spec:
  storageClassName: sc-glusterfs-a
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-conf
  namespace: wsp-sentry
spec:
  storageClassName: sc-glusterfs-a
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-data
  namespace: wsp-sentry
spec:
  storageClassName: sc-glusterfs-a
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-nginx
  namespace: wsp-sentry
spec:
  storageClassName: sc-glusterfs-a
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
