---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-post-process-forwarder
  namespace: wsp-sentry
  labels:
    app: sentry-post-process-forwarder
spec:
  selector:
    matchLabels:
        app: sentry-post-process-forwarder
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry-post-process-forwarder
    spec:
      containers:
      - name: sentry-post-process-forwarder
        image: "srv:7018/wsp_sentry:sentry"
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/local/bin/sentry"
        args:
          - run
          - post-process-forwarder
          - '--commit-batch-size'
          - '1'
        ports:
        - containerPort: 9000
        env:
          - name: SENTRY_REDIS_HOST
            value: 'prod-sentry-db-1.web.s8.ru'
          - name: SENTRY_REDIS_PASSWORD
            value: '12345678'
          - name: SENTRY_MEMCACHED_HOST
            value: memcached-svc
          - name: UWSGI_MAX_REQUESTS
            value: '10000'
          - name: UWSGI_DISABLE_LOGGING
            value: 'true'
          - name: SENTRY_SECRET_KEY
            value: "secret_key"
          - name: SENTRY_CONF
            value: '/etc/sentry'
          - name: SENTRY_FILESTORE_DIR
            value: '/data/files'
          - name: SENTRY_POSTGRES_HOST
            value: 'prod-m1-postgre-site-1.web.s8.ru'
          - name: SENTRY_POSTGRES_PORT
            value: '5432'
          - name: SENTRY_DB_NAME
            value: 'wsp-sentry'
          - name: SENTRY_DB_USER
            value: 'wsp-sentry'
          - name: SENTRY_DB_PASSWORD
            value: '12345678'
          - name: SNUBA
            value: 'http://shuba-api-svc:1218'
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/sentry
          name: config
        resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.2"
              memory: 200Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sentry-data
      - name: config
        persistentVolumeClaim:
          claimName: sentry-conf
